### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by phryk** [flacjacket/pywlroots#1]
Hey there, I'm interested in playing around with writing a wayland compositor but have very little prior wayland knowledge.

Do you consider these bindings stable enough to do that? If so, how would I go about doing that? Could you post a minimal example of a compositor that just starts and displays "Hello World" or whatever? :)

**Comment by flacjacket** [comment]
There is now the `tiny` compositor, which is based off of the example compositor that is given in `wlroots`. https://wayland-book.com/ is a good resource for learning some of the introductory information on wayland. Documentation is definitely something that there will need to be more of, but I think the basic request here should be covered now. Feel free to ask if you have any other questions!

**Comment by phryk** [comment]
Thanks. I've by now kind of opted for learning the D programming language for compositor development, but I still think this is an extremely valuable step towards making pywlroots usable for others. :)
