### ISSUE TITLE
Using functions not inside header files

### ISSUE THREAD

**Issue by Sydiepus** [flacjacket/pywlroots#121]
I don't know much about CFFI and don't understand how it works but,  Is it possible to use functions not inside header files ?
If yes would such code be merged into the repo ?

I was trying to implement a way to control the state of caps lock and num lock from the compositor, however it seems like how it's done is by calling a function (`wlr_keyboard_notify_modifiers`) that the compositor is not supposed to use. (from [sway](https://github.com/swaywm/sway/pull/2330/files))

**Comment by Shinyzenith** [comment]
`wlr_keyboard_notify_modifiers` is present in `wlr/interfaces/wlr_keyboard.h`.

**Comment by Sydiepus** [comment]
Sorry for not reading the includes.
And thank you.
