### ISSUE TITLE
wlroots 0.17.0

### ISSUE THREAD

**Issue by m-col** [flacjacket/pywlroots#126]
Upstream changes for the next release are recorded here: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3527

This thread is for tracking our corresponding changes. I'll start making PRs against a `wlroots-next` branch with changes listed there, and when I do so I'll list them here too. Thus anything mentioned on their thread and not here is a TODO (and PRs welcome!).

Implemented:
- <nothing>

**Comment by flacjacket** [comment]
0.17.0 is out now for wlroots, should we merge `wlroots-next` into `main`?

**Comment by m-col** [comment]
Yep! I have a working Qtile branch on 0.17. Just getting together the last bits of github actions that aren't building
