### ISSUE TITLE
Seat.set_keyboard should accept None

### ISSUE THREAD

**Issue by heuer** [flacjacket/pywlroots#137]
Acc. to <https://wayland.emersion.fr/wlroots/wlr/types/wlr_seat.h.html#func-wlr_seat_set_keyboard> ```NULL``` values are accepted, at least they are not forbidden.

Proposal: Change https://github.com/flacjacket/pywlroots/blob/main/wlroots/wlr_types/seat.py#L232
```python
    def set_keyboard(self, keyboard: Keyboard) -> None:
```
to:
```python
    def set_keyboard(self, keyboard: Keyboard | None) -> None:
```

**Comment by flacjacket** [comment]
Great point!
