### ISSUE TITLE
Replace @classmethod with @staticmethod?

### ISSUE THREAD

**Issue by heuer** [flacjacket/pywlroots#138]
Several classes (Renderer, Allocator, …) have a factory function which does not use the passed ```cls``` argument at all, they can be decorated with ```@staticmethod``` without any difference.

Example: https://github.com/flacjacket/pywlroots/blob/b38b6ceab0a4cf7cc8d755217b365702f59692cb/wlroots/allocator.py#L21

```python
    @classmethod
    def autocreate(cls, backend: Backend, renderer: Renderer) -> Allocator:
        """Creates the adequate allocator given a backend and a renderer."""
        ret = lib.wlr_allocator_autocreate(backend._ptr, renderer._ptr)
        if not ret:
            raise RuntimeError("Unable to create an allocator.")
        return Allocator(ret)
```

**Comment by flacjacket** [comment]
This is a good point, happy to accept a PR for this, otherwise I can change these as I see them.
