### ISSUE TITLE
Roadmap for the project

### ISSUE THREAD

**Issue by heuer** [flacjacket/pywlroots#148]
As I get a little more involved with the project, I'm wondering if another 0.16.x release is planned, or if we should focus on 0.17.x, which will bring some changes anyway.

I would prefer a final release under 0.16.x (maybe addressing #144 and #146 and all previous changes), maybe fixing #134 and #141 might be a useful addition.

But I would probably want to concentrate on wlroots 0.17.x

Do you have any roadmap for this project?

**Comment by flacjacket** [comment]
Thanks for the question! There isn't a particularly firm roadmap for the project other than to serve the needs of whatever libraries are using it and ideally stay as up-to-date as possible. The main user I know of is qtile, but there could be more that I don't know about, so any changes on 0.16 should at least not break that. If there are some good changes to make on 0.16 then I'd be happy to cut a release with those based on all of the PR's that you have put up. Whenever 0.17 is able to compile, we can cut over the main branch to that (there is some work in that direction in the 'wlroots-next` branch that @m-col started, but it still needs some work AFAIK), but even then, there is the `0.16.x` branch that we can cut releases off.

**Comment by flacjacket** [comment]
Sounds good! I'll work on merging your other open PRs in the meantime, just
let me know when would be convenient to cut a release!

**Comment by flacjacket** [comment]
Sure! Sorry for letting those pile up. Is there anything else that would be good to get in for a 0.16 release?
