### ISSUE TITLE
WLR 0.17 - Proposal: Rename XdgTopLevel to XdgToplevel

### ISSUE THREAD

**Issue by heuer** [flacjacket/pywlroots#192]
@flacjacket, @jwijenbergh, maybe we should take the opportunity to rename ``XdgTopLevel`` to ``XdgToplevel`` if we're (partially) breaking backwards compatibility anyway?

The name does not fit the commonly used naming convention.

**Comment by jwijenbergh** [comment]
agreed. done in my branch
