### ISSUE TITLE
Release 0.16.9

### ISSUE THREAD

**Issue by heuer** [flacjacket/pywlroots#194]
@flacjacket, sorry I didn't spot the #189 bug before. I think we should consider 0.16 as feature complete and release another bug fix release. I have summarized my suggestion for this in #190.

I will save the tablet feature (#191) for a 0.17 release; ``wlr_tablet_pad`` still needs to be added to it anyway.

If you agree and find time, you could release 0.16.9 when you get the chance. However, there is no need to rush.

Maybe you can have a look at #182 during the release procedure?

**Comment by flacjacket** [comment]
I just cut this release, we can definitely start moving the `main` towards 0.17 and if we need any bugfixes we can do it out of the `v0.16.x` branch
