### ISSUE TITLE
Get title from XdgTopLevel

### ISSUE THREAD

**Issue by runlevelzero** [flacjacket/pywlroots#2]
Hello, I am trying to read the titles of XdgSurfaces stored in their toplevels, but I am having issues with reading from the char pointer. The issue seems to be with the datatype that I get when I try to reference it.

I have tried using something like this
`xdgSurface.toplevel._ptr.title` to read the data, when I print it it says that it is a `cdata char * type` however, when I check its type using the `type()` function or any of the cffi methods for converting pointers to strings, I see that it is of type `_cffi_backend._CDataBase`. looking this up in the CFFI documentation hasn't turned up much useful information regarding how to turn that into a char* or a python string and I was wondering I you had any insight on how to get the data that this pointer is pointing to

I should also note that `ffi.addressof()` doesn't work for getting the location of the data because it is not a struct or union

thanks

**Comment by flacjacket** [comment]
Hi @runlevelzero, you may have tried it, but I took a pass at what I think would be a fix for this. If you have a test case that can help debug the problem you are having, feel free to re-open this. Thanks!
