### ISSUE TITLE
ImportError on relative import within tinywl

### ISSUE THREAD

**Issue by m-col** [flacjacket/pywlroots#3]
I'm just playing around with tinywl and running `python tinywl` or `python tinywl/__main__.py` gives this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mcol/git/pywlroots/tiny/__main__.py", line 23, in <module>
    from .server import TinywlServer
ImportError: attempted relative import with no known parent package
```
Changing that last import line to `from tiny.server import TinywlServer` fixes it though.

Not sure I get why this is the case though, unless relative imports don't work in files named `__main__.py`?

**Comment by flacjacket** [comment]
Thanks for flagging this. I've added a bit more information on the right way to run this, it should be alright with `python -m tiny`. We can add a different script if that is maybe more obvious how to launch the example.
