### ISSUE TITLE
How can I print wlroots logging?

### ISSUE THREAD

**Issue by m-col** [flacjacket/pywlroots#33]
wlroots compositors in C by default will print logs to stdout but this doesn't seem to be the case with pywlroots. I'm specifically referring to the logging done internal to wlroots, rather than any calls done by the compositor('s own code) to `wlroots.utils.log.logger`, which of course does print to stdout. How can I get these logs printed?

**Comment by flacjacket** [comment]
Do you have any examples you are looking at? If something goes to stdout, we could capture that, but I'm not sure there is a great way to selectively capture logging messages going to stdout and pass through other things that are going to stdout.

**Comment by flacjacket** [comment]
If you are looking to capture wlroots's logging, does running `wlroots.util.log.log_init` solve your problem? That should setup the wlr logging to callback into `log_func_callback` for logging.

**Comment by m-col** [comment]
If I stick `print("hi")` within `log_func_callback` then I see a lot of lines printed to stdout, as expected. I think what's happened is I was expecting a similar signature between:
```c
void wlr_log_init(enum wlr_log_importance verbosity, wlr_log_func_t callback);
```
and
```python
def log_init(log_level: int) -> None
```
I guess the intended usage is to use an interface exposed by the `logging` module to change where the messages end up?

**Comment by m-col** [comment]
This does it:
```python
import logging
from wlroots.util.log import logger, log_init

class PrintHandler(logging.Handler):
    def emit(self, record):
        print(record)

logger.addHandler(PrintHandler())
log_init(logging.DEBUG)

```

**Comment by flacjacket** [comment]
Nice! Does something like this do the trick, too?
```
import logging
from wlroots.util.log import log_init

logging.basicConfig(level=logging.DEBUG)
log_init(logging.DEBUG)
```

**Comment by m-col** [comment]
Yep that works too, I'll use that, thanks.
