### ISSUE TITLE
wlroots 0.14 released

### ISSUE THREAD

**Issue by m-col** [flacjacket/pywlroots#45]
The next major version of wlroots is released: https://github.com/swaywm/wlroots/releases/tag/0.14.0

I went through their changes and the only one that we need to act on is https://github.com/flacjacket/pywlroots/pull/44

Other than that we just need to bump the version.

**Comment by m-col** [comment]
Oh, and probably the versions used by the CI

**Comment by m-col** [comment]
It looks like only the things we mentioned on IRC - libdrm and wayland-protocols - are not met by ubuntu's repos. Building these two things manually appears to be sufficient for wlroots to be happy: https://github.com/qtile/qtile/commit/c5d44a2f2fec410328e9e88c428d1793c7511eb4

**Comment by flacjacket** [comment]
Perfect, that works great here, too. Just cut a new release for 0.14!
