### ISSUE TITLE
cant install on manjaro with pamac or pip

### ISSUE THREAD

**Issue by yobleck** [flacjacket/pywlroots#46]
Attempting to install 0.14.0-1 with pamac
and 0.14.0 with pip.

<details>
<summary>error log</summary>
<br>

Preparing...
Cloning pywlroots build files...
Checking pywlroots dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building pywlroots...
==> Making package: pywlroots 0.14.0-1 (Tue 06 Jul 2021 04:22:33 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v0.14.0.tar.gz
==> Validating source files with sha256sums...
    v0.14.0.tar.gz ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting v0.14.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/wlroots
copying wlroots/ffi_build.py -> build/lib.linux-x86_64-3.9/wlroots
copying wlroots/backend.py -> build/lib.linux-x86_64-3.9/wlroots
copying wlroots/renderer.py -> build/lib.linux-x86_64-3.9/wlroots
copying wlroots/__init__.py -> build/lib.linux-x86_64-3.9/wlroots
copying wlroots/helper.py -> build/lib.linux-x86_64-3.9/wlroots
creating build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/xdg_shell.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/xdg_decoration_v1.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/xdg_output_v1.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/matrix.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/data_control_v1.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/output_damage.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/cursor.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/screencopy_v1.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/data_device_manager.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/server_decoration.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/output_layout.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/xcursor_manager.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/box.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/virtual_keyboard_v1.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/gamma_control_v1.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/pointer.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/compositor.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/texture.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/input_device.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/seat.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/output_management_v1.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/surface.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/keyboard.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/output.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/__init__.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/layer_shell_v1.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
copying wlroots/wlr_types/primary_selection_v1.py -> build/lib.linux-x86_64-3.9/wlroots/wlr_types
creating build/lib.linux-x86_64-3.9/wlroots/util
copying wlroots/util/clock.py -> build/lib.linux-x86_64-3.9/wlroots/util
copying wlroots/util/region.py -> build/lib.linux-x86_64-3.9/wlroots/util
copying wlroots/util/edges.py -> build/lib.linux-x86_64-3.9/wlroots/util
copying wlroots/util/__init__.py -> build/lib.linux-x86_64-3.9/wlroots/util
copying wlroots/util/log.py -> build/lib.linux-x86_64-3.9/wlroots/util
copying wlroots/py.typed -> build/lib.linux-x86_64-3.9/wlroots
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.9/wlroots._ffi.c'
creating build/temp.linux-x86_64-3.9
building 'wlroots._ffi' extension
creating build/temp.linux-x86_64-3.9/build
creating build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIC -DWLR_USE_UNSTABLE -I/usr/include/pixman-1 -I/var/tmp/pamac-build-yobleck/pywlroots/src/pywlroots-0.14.0/include -I/usr/include/python3.9 -c build/temp.linux-x86_64-3.9/wlroots._ffi.c -o build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9/wlroots._ffi.o
build/temp.linux-x86_64-3.9/wlroots._ffi.c: In function ‘_cffi_checkfld_struct_wlr_surface’:
build/temp.linux-x86_64-3.9/wlroots._ffi.c:12155:31: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_below’; did you mean ‘subsurfaces’?
12155 |   { struct wl_list *tmp = &p->subsurfaces_below; (void)tmp; }
      |                               ^~~~~~~~~~~~~~~~~
      |                               subsurfaces
build/temp.linux-x86_64-3.9/wlroots._ffi.c:12156:31: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_above’; did you mean ‘subsurfaces’?
12156 |   { struct wl_list *tmp = &p->subsurfaces_above; (void)tmp; }
      |                               ^~~~~~~~~~~~~~~~~
      |                               subsurfaces
build/temp.linux-x86_64-3.9/wlroots._ffi.c:12157:31: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_pending_below’; did you mean ‘subsurface_pending_list’?
12157 |   { struct wl_list *tmp = &p->subsurfaces_pending_below; (void)tmp; }
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                               subsurface_pending_list
build/temp.linux-x86_64-3.9/wlroots._ffi.c:12158:31: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_pending_above’; did you mean ‘subsurface_pending_list’?
12158 |   { struct wl_list *tmp = &p->subsurfaces_pending_above; (void)tmp; }
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                               subsurface_pending_list
In file included from build/temp.linux-x86_64-3.9/wlroots._ffi.c:61:
build/temp.linux-x86_64-3.9/wlroots._ffi.c: At top level:
build/temp.linux-x86_64-3.9/wlroots._ffi.c:13844:55: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_below’; did you mean ‘subsurfaces’?
13844 |   { "subsurfaces_below", offsetof(struct wlr_surface, subsurfaces_below),
      |                                                       ^~~~~~~~~~~~~~~~~
build/temp.linux-x86_64-3.9/wlroots._ffi.c:13845:60: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_below’; did you mean ‘subsurfaces’?
13845 |                          sizeof(((struct wlr_surface *)0)->subsurfaces_below),
      |                                                            ^~~~~~~~~~~~~~~~~
      |                                                            subsurfaces
In file included from build/temp.linux-x86_64-3.9/wlroots._ffi.c:61:
build/temp.linux-x86_64-3.9/wlroots._ffi.c:13847:55: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_above’; did you mean ‘subsurfaces’?
13847 |   { "subsurfaces_above", offsetof(struct wlr_surface, subsurfaces_above),
      |                                                       ^~~~~~~~~~~~~~~~~
build/temp.linux-x86_64-3.9/wlroots._ffi.c:13848:60: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_above’; did you mean ‘subsurfaces’?
13848 |                          sizeof(((struct wlr_surface *)0)->subsurfaces_above),
      |                                                            ^~~~~~~~~~~~~~~~~
      |                                                            subsurfaces
In file included from build/temp.linux-x86_64-3.9/wlroots._ffi.c:61:
build/temp.linux-x86_64-3.9/wlroots._ffi.c:13850:63: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_pending_below’; did you mean ‘subsurface_pending_list’?
13850 |   { "subsurfaces_pending_below", offsetof(struct wlr_surface, subsurfaces_pending_below),
      |                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~
build/temp.linux-x86_64-3.9/wlroots._ffi.c:13851:68: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_pending_below’; did you mean ‘subsurface_pending_list’?
13851 |                                  sizeof(((struct wlr_surface *)0)->subsurfaces_pending_below),
      |                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                    subsurface_pending_list
In file included from build/temp.linux-x86_64-3.9/wlroots._ffi.c:61:
build/temp.linux-x86_64-3.9/wlroots._ffi.c:13853:63: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_pending_above’; did you mean ‘subsurface_pending_list’?
13853 |   { "subsurfaces_pending_above", offsetof(struct wlr_surface, subsurfaces_pending_above),
      |                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~
build/temp.linux-x86_64-3.9/wlroots._ffi.c:13854:68: error: ‘struct wlr_surface’ has no member named ‘subsurfaces_pending_above’; did you mean ‘subsurface_pending_list’?
13854 |                                  sizeof(((struct wlr_surface *)0)->subsurfaces_pending_above),
      |                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                    subsurface_pending_list
error: command '/sbin/gcc' failed with exit code 1
==> ERROR: A failure occurred in build().
    Aborting... 

</details>

All dependencies are installed and up to date:

python-setuptools-scm              5.0.2-1                     community  124.4 kB
wlroots                            0.13.0-1                    community  993.3 kB
python-xkbcommon                   0.3-1                       AUR        194.0 kB
pywayland                          0.4.4-1                     AUR        1.9 MB
python-cffi                        1.14.5-1                    extra      1.1 MB

inxi -S output:
`Kernel: 5.10.42-1-MANJARO x86_64 Desktop: Qtile 0.17.0 Distro: Manjaro Linux`

**Comment by flacjacket** [comment]
Hi @yobleck! Thanks for the report. The versioning of pywlroots is setup to match the version of wlroots in major/minor versions. So, for wlroots 0.13.0, you would need one of the pywlroots versions `0.13.x`. Looking at the traceback, that is not obvious. I think we can make the error message more clear so this is clear.

Do you have a link to the package in manjaro? I would report downstream that the dependencies of the pywlroots should be set based on the wlroots version.

**Comment by yobleck** [comment]
arch user repo website: https://aur.archlinux.org/packages/pywlroots

It says the maintainer is @m-col so I suppose they'll get around to it if they see this and when it's convenient for them (no rush)

In the mean time I successfully installed version 0.13.5 via pip. Also the AUR says the current version of wlroots is 0.14 so I think I just need to force an update or something.

Thanks for the help :)

**Comment by m-col** [comment]
Hey @yobleck, thanks for bringing it up. I've set the pywlroots AUR version to be the latest release, but I guess instead it could/should match the wlroots version from the official repos in case they are not up to date themselves with the latest wlroots release.

However, looking at the official package for wlroots - https://archlinux.org/packages/community/x86_64/wlroots/ - they are at 0.14.0 so perhaps you need to update that and then re-install.

**Comment by flacjacket** [comment]
Thanks for checking @m-col!

I added a new pair of releases, 0.13.6 and 0.14.1, which add wlroots version checks on install, and should help users in figuring this out on their own.
