### ISSUE TITLE
Tests missing in pypi sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [flacjacket/pywlroots#49]
Hi! I'm currently starting to package python-pywlroots on Arch Linux for qtile.
We usually run tests against the build to ensure compatibility with the rest of the system. Especially when building wrappers for C libraries this is very important to detect problems as early as possible (upon rebuild).

It would be really great, if you could include the tests directory in the sdist tarball! :)

**Comment by flacjacket** [comment]
This should be available in 0.14.3, thanks for taking care of getting everything packaged! Let us know if there anything else you need there.

**Comment by dvzrv** [comment]
Thanks! 0.14.3 fixes this for me! :)
