### ISSUE TITLE
Tracking wlroots releases

### ISSUE THREAD

**Issue by m-col** [flacjacket/pywlroots#5]
How do you manage compatibility with wlroots releases? Currently pywlroots only supports wlroots 0.12.0, whereas wlroots is currently on 0.13.0 (only recently). Between releases they track breaking changes in an issue such as this for 0.14.0: https://github.com/swaywm/wlroots/issues/2844. Do you aim to exclusively support the current release or maintain some kind of backwards compatibility?

**Comment by m-col** [comment]
Just saw that you did update to work with 0.13.0 so ignore that part :)

**Comment by flacjacket** [comment]
This is a great question. With wayland, it looks like everything is generally added in a nice backwards compatible way, and then through the protocols, that we can generally keep track of our own versions. But I was thinking it might make sense to change the versioning here to keep inline with the wlroots version that is supported. So something like 0.13.x, where our bugfixes can be new patch versions, but signifying that it supports wlroots 0.13. While we are still in the early phase, supporting the latest version is probably good enough, we can try to maintain backwards compatible support as much as makes sense and as much as it makes sense to keep up the support for the older versions. In which case, having the versions following the wlroots version would make keeping separate branches alive for separate versions easier. That is probably more maintenance than we need at this point, but a good thing to think about as we move this into qtile and need to support it more.

**Comment by flacjacket** [comment]
Happy to have thoughts or feedback on the best way to version this and maintain support for upstream wlroots functionality!

**Comment by m-col** [comment]
Oops forgot to reply. I noticed you changed the version to 0.13.0. Yeah that sounds like a nice approach, just like you suggested above. 

>  In which case, having the versions following the wlroots version would make keeping separate branches alive for separate versions easier. That is probably more maintenance than we need at this point, but a good thing to think about as we move this into qtile and need to support it more.

Agreed completely. If people really wanted to they could package the latest 0.13.x version as pywlroots-0.13 after we're done with it, if they wanted to keep using the older version.

**Comment by flacjacket** [comment]
Sounds good. Yeah, that agrees with how I was seeing that.
