### ISSUE TITLE
Arch linux package out of date

### ISSUE THREAD

**Issue by Sydiepus** [flacjacket/pywlroots#87]
Package in [arch linux repo](https://archlinux.org/packages/community/x86_64/python-pywlroots/) is out of date. 

It has been flagged as out-of-date a couple days ago.

Sorry if this is not the right place to report it.

**Comment by flacjacket** [comment]
It looks like @dvzrv is the maintainer of that package, is it possible to bump that? Thanks!

**Comment by dvzrv** [comment]
@Sydiepus Please refer to the [downstream documentation](https://wiki.archlinux.org/title/Frequently_asked_questions#Upstream_project_X_has_released_a_new_version._How_long_will_it_take_for_the_Arch_package_to_update_to_that_new_version?).
@flacjacket This ticket can be closed I guess. I will upgrade as soon as I have access to build infrastructure (likely around Tuesday).

**Comment by flacjacket** [comment]
Thank for the info! It looks like the flag is the right thing needed to get the update going, so I agree to close this out here.

**Comment by Sydiepus** [comment]
Sorry for not reading the documentation and thank you for maintaining the package.
